Retry unmounts on error
Try to unmount for 10 seconds, then give up and tell the user what they
can do.

diff --git a/tmpchroot b/tmpchroot
--- a/tmpchroot
+++ b/tmpchroot
@@ -82,7 +82,23 @@ mountbinds() {
 umountbinds() {
     for i in $(seq $((${#bindmounts[@]} - 1)) -1 0); do
         if grep -q "$(realpath "$newROOT/${bindmounts[$i]}")" /etc/mtab; then
-            umount "$newROOT/${bindmounts[$i]}"
+            j=1
+            while ! umount "$newROOT/${bindmounts[$i]}" 2>/dev/null; do
+                echo "WARNING: Try $j of unmount failed for" \
+                    "$newROOT/${bindmounts[$i]}"
+
+                if [ "$j" -ge 5 ]; then
+                    echo "ERROR: Giving up, please close all accesses to"
+                    echo "  $newROOT/${bindmounts[$i]}"
+                    echo "  manually and call"
+                    echo "  \`$0 delete $envname\`"
+                    echo "  afterwards!"
+                    exit 1
+                fi
+
+                j=$((j + 1))
+                sleep 2
+            done
         fi
     done
 }
